import type { ObjectDef } from '../types.js';

export const Campaign: ObjectDef = {
  nameSingular: 'campaign',
  namePlural: 'campaigns',
  labelSingular: 'Campaign',
  labelPlural: 'Campaigns',
  description: 'Marketing campaign — goal, offer, persona, AI/ad budget, status.',
  icon: 'IconRocket',
  fields: [
    {
      name: 'name',
      label: 'Name',
      type: 'TEXT',
      isNullable: false,
      description: 'Internal campaign name. Used in slugs and reports.',
    },
    {
      name: 'goal',
      label: 'Goal',
      type: 'TEXT',
      description: 'What this campaign tries to achieve. Used by AI to guide copy.',
    },
    {
      name: 'offer',
      label: 'Offer',
      type: 'RICH_TEXT',
      description: 'The value proposition shown to leads.',
    },
    {
      name: 'persona',
      label: 'Persona',
      type: 'RAW_JSON',
      description: 'Target persona object: role, industry, pain, language.',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'SELECT',
      defaultValue: 'draft',
      isNullable: false,
      options: [
        { value: 'draft', label: 'Draft', color: 'gray', position: 0 },
        { value: 'pending_review', label: 'Pending Review', color: 'yellow', position: 1 },
        { value: 'approved', label: 'Approved', color: 'blue', position: 2 },
        { value: 'live', label: 'Live', color: 'green', position: 3 },
        { value: 'paused', label: 'Paused', color: 'orange', position: 4 },
        { value: 'completed', label: 'Completed', color: 'purple', position: 5 },
        { value: 'failed', label: 'Failed', color: 'red', position: 6 },
      ],
    },
    {
      name: 'aiBudgetNok',
      label: 'AI Budget (NOK)',
      type: 'CURRENCY',
      defaultValue: 200,
      settings: { currencyCode: 'NOK' },
      description: 'Max AI spend for this campaign. Hard stop at limit.',
    },
    {
      name: 'aiSpentNok',
      label: 'AI Spent (NOK)',
      type: 'CURRENCY',
      defaultValue: 0,
      settings: { currencyCode: 'NOK' },
      description: 'Auto-incremented by control-api on each AI call.',
    },
    {
      name: 'adBudgetNok',
      label: 'Ad Budget (NOK)',
      type: 'CURRENCY',
      defaultValue: 5000,
      settings: { currencyCode: 'NOK' },
    },
    {
      name: 'adSpentNok',
      label: 'Ad Spent (NOK)',
      type: 'CURRENCY',
      defaultValue: 0,
      settings: { currencyCode: 'NOK' },
    },
    {
      name: 'startDate',
      label: 'Start Date',
      type: 'DATE',
    },
    {
      name: 'endDate',
      label: 'End Date',
      type: 'DATE',
    },
    {
      name: 'reviewNotes',
      label: 'Review Notes',
      type: 'RICH_TEXT',
      description: 'Reviewer comments during pending_review.',
    },
    {
      name: 'failureReason',
      label: 'Failure Reason',
      type: 'TEXT',
    },
  ],
  relations: [
    {
      name: 'landingPages',
      label: 'Landing Pages',
      cardinality: 'ONE_TO_MANY',
      targetObject: 'landingPages',
      targetFieldName: 'campaign',
      targetFieldLabel: 'Campaign',
    },
    {
      name: 'ads',
      label: 'Ads',
      cardinality: 'ONE_TO_MANY',
      targetObject: 'ads',
      targetFieldName: 'campaign',
      targetFieldLabel: 'Campaign',
    },
  ],
};
